baseurl = "/"
languageCode = "de-de"
title = "Carbon Drive Ihre CFK-Experten"
theme = "hugo-creative-theme"

[params]

  # You can use Markdown syntax for urls [text](//url.to/source) for
  # most longer texts.

  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # All projects of the portfolio are defined in their own files.
  # You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
  # folder into the 'data' directory at the root of this Hugo site.
  # For more informtion take a look at the README.

  # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
  name = "Carbon-Drive GmbH"
  description = "CFK-Motorspindeln und Komponenten von Carbon-Drive: Leichter. Präziser. Schneller."

  # The path must be relative to the static folder
  favicon = "favicon.ico"

  # Unsere Vorlaeufige Farbe ist #162B4B

  # Navigation
  [params.navigation]
    brand = "Carbon-Drive"

    [[params.navigation.links]]
      target = "vorteile"
      text = "Vorteile CFK"
      [[params.navigation.links]]
        target = "msp_data"
        text = "CFK-Motorspindel"
      [[params.navigation.links]]
        target = "msp_ergebnis"
        text = "Ergebnis CFK-Motorspindel"
      [[params.navigation.links]]
        target = "services"
        text = "Unsere Leistungen"
      [[params.navigation.links]]
        target = "team"
        text = "Kontakt"

    [[menu.main]]
          name = "Blog"
          identifier = "post"
          url = "/post/"

  # Hero section
  [params.hero]
    # To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
    subtitle     = "Leichter. Präziser. Schneller."
    slogan   = "CFK-Motorspindeln und Komponenten von Carbon-Drive"
    buttonText = "Finden Sie mehr heraus!"

  # About section
  [params.ziel]
    headline    = "Unser Ziel"
    description = """Die leichtbauoptimalen Werkstoffeigenschaften von CFK nutzen, um den nächsten Technologiesprung im Werkzeugmaschinenbau einzuleiten. """
    buttonText  = "Welche Vorteile hat der Einsatz von CFK?"

  # Vorteile section
    [params.vorteile]
      headline = "Vorteile durch CFK"
      buttonText  = "Wo kann man diese Vorteile optimal Nutzen?"
            [[params.vorteile.list]]
                title = "Werkstoffvorteile von CFK"
                [[params.vorteile.list.list]]
                  item = "geringe Masse"
                [[params.vorteile.list.list]]
                  item = "hohe Steifigkeit"
                [[params.vorteile.list.list]]
                  item = "keine thermische Ausdehnung"
                [[params.vorteile.list.list]]
                  item = "additive Fertigungsverfahren"
            [[params.vorteile.list]]
                title = "Benefit für Werkzeugmaschinen"
                [[params.vorteile.list.list]]
                  item = "kürzere Bearbeitungszeiten"
                [[params.vorteile.list.list]]
                  item = "geringerer Energiebedarf"
                [[params.vorteile.list.list]]
                  item = "höhere Präzision"
                [[params.vorteile.list.list]]
                  item = "Sensorintegration an beliebiger Stelle"
            [[params.vorteile.list]]
                title = "Wirtschaftlicher Erfolg"
                summary = "Gewinnsteigerung"
                [[params.vorteile.list.list]]
                  item = "höhere Produktivität"
                [[params.vorteile.list.list]]
                  item = "geringere Betriebskosten"

  # msp_claim section
  [params.msp_claim]
    headline    = "CFK-Motorspindeln"
    description = " Der Einsatz von CFK erschließt gerade bei dem Herzstück der Werkzeugmaschine ein komplett neues Leistungsspektrum."
    buttonText = "Wie sieht die erste Motorspindel der Zukunft aus?"

  # msp_data section
    [params.msp_data]
      headline = "Daten der ersten Voll-Carbon-Motorspindel"
      buttonText  = "Wie sieht der Vergleich zu einer Stahlspindel aus?"
            [[params.msp_data.list]]
                title = "Drehzahl"
                [[params.msp_data.list.list]]
                  item = "35.000 rpm"
            [[params.msp_data.list]]
                title = "Leistung"
                [[params.msp_data.list.list]]
                  item = "10 kW"
            [[params.msp_data.list]]
                title = "Durchmesser"
                [[params.msp_data.list.list]]
                  item = "Ø 109 mm"
            [[params.msp_data.list]]
                title = "Länge"
                [[params.msp_data.list.list]]
                  item = "190 mm"
            [[params.msp_data.list]]
                title = "Gewicht"
                [[params.msp_data.list.list]]
                    item = "5 kg"
            [[params.msp_data.list]]
                title = "Werkzeugschnittstelle"
                [[params.msp_data.list.list]]
                  item = "HSK-A40"
            [[params.msp_data.list]]
                title = "Lagerschilde"
                [[params.msp_data.list.list]]
                  item = "CFK-Pressteile"
            [[params.msp_data.list]]
                title = "Welle & Gehäuse"
                [[params.msp_data.list.list]]
                  item = "CFK-Wickelteile"
            [[params.msp_data.list]]
                title = "Lagerung"
                [[params.msp_data.list.list]]
                  item = "4 Stk. Hochgeschindigkeits Hybridlager"
                [[params.msp_data.list.list]]
                  item = "fettgeschmiert"
                [[params.msp_data.list.list]]
                  item = "starr angestellt"
            [[params.msp_data.list]]
                title = "Positionieren"
                [[params.msp_data.list.list]]
                  item = "Drehgeber mit Referenzfahne"
            [[params.msp_data.list]]
                title = "Kühlung"
                [[params.msp_data.list.list]]
                  item = "2,2 kW- Flüssigkeitskühlkreislauf"
            [[params.msp_data.list]]
                title = "Motorbauart"
                [[params.msp_data.list.list]]
                  item = "Permanentmagnet-erregter Synchronmotor"
  # cfk_vs_stahl section
  [params.cfk_vs_stahl]
    headline    = "Einschätzung der CFK-Motorspindel"
    description = "Die 10-kW CFK-Motorspindel schafft es bei halbem Masseneinsatz, die Präzision und Geschwindigkeit der Stahl-Motorspindel zu übertreffen!"
    buttonText = "Was heißt das konkret?"

  # MSP Ergebnis section
  [params.msp_ergebnis]
    headline = "CFK- vs. Stahl-Motorspindel"
    buttonText  = "Wie kann ich von diesem Know-How profitieren?"
      [[params.msp_ergebnis.list]]
        icon = "glyphicon glyphicon-scale"
        title = "50% Leichter"
        description = "Massenreduktion senkt Energiebedarf, Nebenzeiten und somit Kosten."

      [[params.msp_ergebnis.list]]
        icon = "fa fa-crosshairs"
        title = "90% Präziser"
        description = "Keine thermische Dehnung steigert Präzision und Oberflächenqualität"

      [[params.msp_ergebnis.list]]
        icon = "fa fa-dashboard"
        title = "50% Schneller"
        description = "Bei allen Beschleunigungsvorgängen"

      [[params.msp_ergebnis.list]]
        icon = "fa fa-lightbulb-o"
        title = "Intelligenter"
        description = "Smarte Bauteile mit lokal angepassten Werkstoffeigenschaften durch additive Bauweisen"
  # cfk_vs_stahl section
  [params.services_claim]
    headline    = "Unser Know-How, Ihr Gewinn"
    description = "Gerne entwickeln, berechnen und realisieren wir für Sie individuelle CFK-Motorspindeln und Komponenten!  "
    buttonText = "Welche Services bietet Carbon-Drive an?"


  # Service section
  [params.services]
    headline = "Unser Service für Sie:"
    buttonText  = "Wer sind Ihre Ansprechpartner?"
        [[params.services.list]]
            icon = "icon_entwickeln"
            title = "Entwicklung"
            description = "Konzeption nach Ihren Bedürfnissen, Weiter- und Neuentwicklungen, Chancen aufzeigen."

        [[params.services.list]]
           icon = "icon_auslegen"
           title = "Engineering"
           description = "Konstruktion, Berechnung & Optimierung"

        [[params.services.list]]
            icon = "icon_herstellen"
            title = "Herstellung"
            description = "Prototypen, Testen & Produktion"
    # Team section
    [params.team]
      headline    = "Das Management-Team"
      description = ""
    # Portfolio modals
  [params.portfolio.modal]
        client = "Ansprechpartner"
        date = "Datum"
        category = "Kategorie"
        buttonText = "Schließen"
  # Portfolio modals
  [params.team_portfolio.modal]
            client = "Kontakt"
            date = "Datum"
            mail = "E-Mail"
            phone = "Telefon"
            category = "Position"
            buttonText = "Schließen"
    # Projekte section
  [params.projekte]
    headline    = "Das Projekt"
    description = """Das erklärte Ziel ist es die besten Spindelwellen der Welt zu bauen.
                   Dieses Projekt haben wir in mehrere Arbeitspakete unterteilt:
                   1. Eigenschaften des Referenzsystems mit Stahlwelle ermitteln
                   2. Einbau der CFK-Spindelwelle
                   3. Eigenschaften des Systems mit CFK-Spindelwelle ermitteln """
    buttonText  = "Zu den Teilprojekten!"


  # Contact section
  [params.contact]
    headline = "Stellen Sie uns Fragen!"
    description = "Sind Sie bereit für den nächsten Schritt auf dem Weg zu höchster Präzision? Dann rufen Sie uns an oder schreiben Sie uns eine Email. Wir freuen uns darauf Sie voran zubringen!"
    phone = "+49-6151-16-22026"
    email = "info@carbon-drive.de"
