baseurl = "/"
languageCode = "de-de"
title = "Carbon Drive Ihre CFK-Experten"
#theme = "hugo-creative-theme"

[params]

  # You can use Markdown syntax for urls [text](//url.to/source) for
  # most longer texts.

  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # All projects of the portfolio are defined in their own files.
  # You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
  # folder into the 'data' directory at the root of this Hugo site.
  # For more informtion take a look at the README.

  # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
  name = "Carbon-Drive GmbH"
  description = "CFK-Motorspindeln und Komponenten: Leichter. Präziser. Schneller."

  # The path must be relative to the static folder
  favicon = "favicon.ico"

  # Unsere Vorlaeufige Farbe ist #162B4B

  # Navigation
  [params.navigation]
    brand = "Carbon-Drive"

    [params.navigation.links]
      ziel     = "Unser Ziel"
      vorteile      = "Vorteile CFK"
      msp_claim  = "Ihre Vorteile"
      portfolio = "Das Projekt"
      contact   = "Ihre Ansprechpartner"
      blog   = "Blog"

    [[menu.main]]
          name = "Blog"
          identifier = "post"
          url = "/post/"

  # Hero section
  [params.hero]
    # To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
    slogan     = "Leichter. Präziser. Schneller."
    subtitle   = "CFK-Motorspindeln und Komponenten von Carbon-Drive"
    buttonText = "Finden Sie mehr heraus!"

  # About section
  [params.ziel]
    headline    = "Unser Ziel"
    description = """Die leichtbauoptimalen Werkstoffeigenschaften von CFK nutzen, um den nächsten Technologiesprung im Werkzeugmaschinenbau einzuleiten. """
    buttonText  = "Welche Vorteile hat der Einsatz von CFK?"

  # Vorteile section
    [params.vorteile]
      headline = "Vorteile durch CFK"
      buttonText  = "Wo kann man diese Vorteile optimal Nutzen?"
            [[params.vorteile.list]]
                title = "Werkstoffvorteile von CFK"
                [[params.vorteile.list.list]]
                  item = "geringe Masse"
                [[params.vorteile.list.list]]
                  item = "hohe Steifigkeit"
                [[params.vorteile.list.list]]
                  item = "keine thermische Ausdehnung"
                [[params.vorteile.list.list]]
                  item = "additive Fertigungsverfahren"
            [[params.vorteile.list]]
                title = "Benefit für Werkzeugmaschinen"
                [[params.vorteile.list.list]]
                  item = "kürzere Bearbeitungszeiten"
                [[params.vorteile.list.list]]
                  item = "geringerer Energiebedarf"
                [[params.vorteile.list.list]]
                  item = "höhere Präzision"
                [[params.vorteile.list.list]]
                  item = "Sensorintegration an beliebiger Stelle"
            [[params.vorteile.list]]
                title = "Wirtschaftlicher Erfolg"
                summary = "Gewinnsteigerung"
                [[params.vorteile.list.list]]
                  item = "höhere Produktivität"
                [[params.vorteile.list.list]]
                  item = "geringere Betriebskosten"

  # msp_claim section
  [params.msp_claim]
    headline    = "CFK-Motorspindeln"
    description = " Der Einsatz von CFK erschließt gerade bei dem Herzstück der Werkzeugmaschine ein komplett neues Leistungsspektrum."
    buttonText = "Wie sieht die erste Motorspindel der Zukunft aus?"

  # msp_data section
    [params.msp_data]
      headline = "Daten der ersten Voll-Carbon-Motorspindel"
      buttonText  = "Wie sieht der Vergleich zu einer Stahlspindel aus?"
            [[params.msp_data.list]]
                title = "Drehzahl"
                [[params.msp_data.list.list]]
                  item = "35.000 rpm"
            [[params.msp_data.list]]
                title = "Leistung"
                [[params.msp_data.list.list]]
                  item = "10 kW"
            [[params.msp_data.list]]
                title = "Durchmesser"
                [[params.msp_data.list.list]]
                  item = "Ø 109 mm"
            [[params.msp_data.list]]
                title = "Länge"
                [[params.msp_data.list.list]]
                  item = "190 mm"
            [[params.msp_data.list]]
                title = "Werkzeugschnittstelle"
                [[params.msp_data.list.list]]
                  item = "HSK-A40"
            [[params.msp_data.list]]
                title = "Lagerschilde"
                [[params.msp_data.list.list]]
                  item = "CFK-Pressteile"
            [[params.msp_data.list]]
                title = "Welle & Gehäuse"
                [[params.msp_data.list.list]]
                  item = "CFK-Wickelteile"
            [[params.msp_data.list]]
                title = "Lagerung"
                [[params.msp_data.list.list]]
                  item = "4 Stk. Hochgeschindigkeits Hybridlager"
                [[params.msp_data.list.list]]
                  item = "fettgeschmiert"
                [[params.msp_data.list.list]]
                  item = "starr angestellt"
            [[params.msp_data.list]]
                title = "Positionieren"
                [[params.msp_data.list.list]]
                  item = "Drehgeber mit Referenzfahne"
            [[params.msp_data.list]]
                title = "Kühlung"
                [[params.msp_data.list.list]]
                  item = "2,2 kW- Flüssigkeitskühlkreislauf"
            [[params.msp_data.list]]
                title = "Motorbauart"
                [[params.msp_data.list.list]]
                  item = "Permanenterregter Synchronmotor"
  # MSP Ergebnis section
  [params.msp_ergebnis]
    headline = "CFK vs. Stahl"
    buttonText  = "Wie geht es weiter?"
      [[params.msp_ergebnis.list]]
        icon = "glyphicon glyphicon-scale"
        title = "50% Leichter"
        description = "Massenreduktion senkt Energiebedarf, Nebenzeiten und somit Kosten."

      [[params.msp_ergebnis.list]]
        icon = "fa fa-crosshairs"
        title = "90% Präziser"
        description = "Keine thermische Dehnung steigert Präzision und Oberflächenqualität"

      [[params.msp_ergebnis.list]]
        icon = "fa fa-dashboard"
        title = "50% Schneller"
        description = "Bei allen Beschleunigungsvorgängen"

      [[params.msp_ergebnis.list]]
        icon = "fa fa-lightbulb-o"
        title = "Intelligenter"
        description = "Smarte Bauteile mit lokal angepassten Werkstoffeigenschaften durch additive Bauweisen"

  # Team section
  [params.team]
    headline    = "Das Team"
    description = "Wir sind ein junges Spin-Off der Fachgebiets Konstruktiver Leichtbau und Bauweisen. Im einzelnen Dr.-Ing. Martin Klimach, Dr.-Ing. Jakob Katz, Alexander Brechtel, M.Sc. und Volker Rosmann"

  # Service section
  [params.services]
    headline = "Ihre Vorteile"
    buttonText  = "Welche Gesichter stecken hinter Carbon-Drive"
        [[params.services.list]]
            icon = "fa-diamond"
            title = "Kohlenstoff: Der Zukunftswerkstoff"
            description = "Mit unseren hochsteifen Kohlenstofffasern werden Ihre Werkzeugmaschinen schneller und präziser."

        [[params.services.list]]
           icon = "fa-graduation-cap"
           title = "Unser Know-Kow ist unschlagbar"
           description = "Wir legen Ihre Spindelwelle nach neusten wissenschaftlichen Erkenntnissen aus!"

        [[params.services.list]]
            icon = "fa-crosshairs"
            title = "Präzision und Qualität"
            description = "Unsere CFK-Spindelwellen erfüllen auch Ihre höchsten Ansprüche!"

    [[params.services.list]]
            icon = "fa-line-chart"
            title = "Wir steigern Ihren Gewinn"
            description = "Mit unseren Spindelwellen können Sie schneller präzise fertigen."

    # Portfolio modals
  [params.portfolio.modal]
        client = "Ansprechpartner"
        date = "Datum"
        category = "Kategorie"
        buttonText = "Schließen"
  # Portfolio modals
  [params.team_portfolio.modal]
            client = "Kontakt"
            date = "Datum"
            mail = "E-Mail"
            phone = "Telefon"
            category = "Position"
            buttonText = "Schließen"
    # Projekte section
  [params.projekte]
    headline    = "Das Projekt"
    description = """Das erklärte Ziel ist es die besten Spindelwellen der Welt zu bauen.
                   Dieses Projekt haben wir in mehrere Arbeitspakete unterteilt:
                   1. Eigenschaften des Referenzsystems mit Stahlwelle ermitteln
                   2. Einbau der CFK-Spindelwelle
                   3. Eigenschaften des Systems mit CFK-Spindelwelle ermitteln """
    buttonText  = "Zu den Teilprojekten!"


  # Contact section
  [params.contact]
    headline = "Stellen Sie uns Fragen!"
    description = "Sind Sie bereit für den nächsten Schritt auf dem Weg zu höchster Präzision? Dann rufen Sie uns an oder schreiben Sie uns eine Email. Wir freuen uns darauf Sie voran zubringen!"
    phone = "+49-6151-16-22026"
    email = "info@carbon-drive.de"
